apps/envio/urls.py
from django.conf.urls import url
from .views import index,envioUpload

urlpatterns = [
    url(r'^$', index.as_view(),name='index'),
    url(r'^upload_file$', envioUpload.as_view(),name='upload_file'),
]

envioxls/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from apps.envio.urls import urlpatterns as enviopatterns

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^envio/',include(enviopatterns,namespace="envio")),
]

apps/envio/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class FileSave(models.Model):
    mi_archivo = models.FileField(upload_to='media/files/')

apps/envio/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.forms import FileInput

class UploadFileForm(forms.Form):
    cargar  = forms.FileField(        
	label="Carga de archivo",
    )

apps/envio/views.py
from django.shortcuts import render
from django.views.generic import TemplateView,View
from django.core.files import File
from .forms import UploadFileForm
from .models import FileSave
from openpyxl import load_workbook
from ODSReader import ODSReader

# Create your views here.
class index(TemplateView):
    template_name = 'envio/index.html'
    
class envioUpload(TemplateView):
    template_name = 'envio/envio_upload.html'
    
    def get(self,request):
        form = UploadFileForm()
        return render(request,self.template_name, {'form': form})
    
    def post(self,request):
        error = ''
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            archivo = request.FILES['cargar']
            extension = str(archivo).split('.')[1]
            if(extension=='xlsx'):
                my_dict = self.xlsx(archivo)
                return render(request,'envio/tablaenvio.html', {'my_dict': my_dict})
            elif(extension=='ods'):
                m = FileSave(mi_archivo=request.FILES['cargar'])
                m.save()
                my_dict = self.ods(m.mi_archivo)
                return render(request,'envio/tablaenvio.html', {'my_dict': my_dict})
            else:
                print "solo se permiten archivos xlsx y ods"
                error = "solo se permiten archivos xlsx ods"
                return render(request,self.template_name, {'form': form,'error':error})
        else:
            print form.errors
        return render(request,self.template_name, {'form': form})
    
    def xlsx(self,archivo):
        wb = load_workbook(archivo)
        ws = wb.active
        filas = len(ws.rows)
        columnas = len(ws.columns)
        my_dict = {}
        for i in range(1,columnas+1):
            my_dict[ws.cell(row=1,column=i).value] = []
        
        for i in range(1,columnas+1):
            nombre = ws.cell(row=1,column=i).value
            for j in range(2,filas+1):
                my_dict[nombre].append(ws.cell(row=j,column=i).value)
        return my_dict
    
    def ods(self,archivo):
        my_file = open(str(archivo),'rb')
        doc = ODSReader(my_file, clonespannedcolumns=True)
        table = ''
        try:
            table = doc.getSheet(u'Sheet1')
        except:
            table = doc.getSheet(u'Hoja1')
        my_dict = {}
        for i in range(len(table)):
            for j in range(len(table[i])):
                if(i==0):
                    my_dict[table[i][j]] = []
                else:
                    my_dict[table[0][j]].append(table[i][j])
        print my_dict
        return my_dict

templates/base.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
{% load staticfiles %}
<html>
    <head>
        <title>{% block title %}{% endblock %}</title>
        {% block css %}
        <link rel="stylesheet" href="{% static "css/style.css" %}">
        <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
        {% endblock %}
    </head>
    <body>
        <div id="contenedor">
            <div id="cabecera">
                {% block cabecera %}
                <h1 style="text-align: center">Envio de xlsx y odt</h1>
                <hr>
                {% endblock %}
            </div>
            <div id = "cuerpo">
                <div id="menu">
                    {% block menu %}
                    <h3>Menú</h3><hr>
                    <ul class="nav nav-pills nav-stacked">
                        <li><a href="{% url 'envio:index'%}"><h3>Inicio</h3></a></li>
                        <li><a href="{% url 'envio:upload_file'%}"><h3>Cargar</h3></a></li>
                    </ul>
                    {% endblock %}
                </div>
                <div id="contenido">
					<div class="container">
						<div class="row">
							{% block contenido %}
							{% endblock %}
						</div>
                    </div>
                </div>
            </div>
            <div id="pie">
                {% block pie %}
                    <p>Rodrigo Boet. 2016</p>
                {% endblock %}
            </div>
        </div>

    </body>
</html>

templates/envio/envio_upload.html
{% extends 'base.html' %}
{%block title%}
    Envio
{%endblock%}

{%block contenido%}
    <h1>Carga de Archivos</h1><hr>
    <form action="{% url 'envio:upload_file' %}" method="post" enctype="multipart/form-data" role="form">
        {% csrf_token %}
        <div class="container">
			<div class="row">
				<div class="form-group">
					<div class="col-md-2">
						<label>{{ form.cargar.label }}</label>
					</div>
					<div class="col-md-10">
						{{form.cargar}}
					</div>
				</div>
			</div>
			<div class="row">
				<button class="btn btn-primary">Enviar</button>
			</div>
        </div>
    </form>
    <p>{{error}}</p>  
{%endblock%}

templates/envio/index.html
{% extends 'base.html' %}
{%block title%}
    Inicio
{%endblock%}

{%block contenido%}
    <h1 style="text-align: center">Bienvenido a Django 1.9</h1>
{%endblock%}

templates/envio/tablaenvio.html
{% extends 'base.html' %}
{%block title%}
    Tabla
{%endblock%}

{%block contenido%}
    <h1>Tabla de Carga</h1>
    <table class="table" >
        <tbody>
        {% for key,val in my_dict.items %}
            <tr>
                <td><b>{{key}}</b></td>
                {%for item in val%}
                    <td>{{item}}</td>
                {%endfor%}
            </tr>
        {% endfor %}
        </tbody>
    </table>
{%endblock%}